Fix on-launch error message for 'headedServerSetupModel' being null
On launch of headed game client, observed error with pop-up:

> java.lang.NullPointerException: Cannot invoke "games.strategy.engine.framework.startup.ui.panels.main.HeadedServerSetupModel.getUi()" because "org.triplea.game.client.HeadedGameRunner.headedServerSetupModel" is null
	at org.triplea.game.client.HeadedGameRunner.start(HeadedGameRunner.java:193)
	at org.triplea.game.client.HeadedGameRunner.main(HeadedGameRunner.java:168)

Problem is the initialization of 'headedServerSetupModel' to a non-null value is done on a new thread. We spawn that thread and immediately use a needed value from 'headedServerSetupModel'.