IntelliJ IDEA Updates (Windows)
- Paths corrected according to steps performed on a windows new installation.
- Screenshots added
Currently still the gradle task build is failing with the following error which seems to be something that should be solved in the code, but it is no setup issue.
Please review and give feedback.

C:\Users\evond\git\triplea\java-extras\src\main\java\org\triplea\java\Retryable.java:17: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
  private static final Consumer<Duration> DEFAULT_THREAD_SLEEP =
                                          ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.3.4
     BugPattern: UnnecessaryLambda
     Stack Trace:
     java.lang.LinkageError: com.sun.tools.javac.comp.Resolve.findIdent(com.sun.tools.javac.comp.Env,com.sun.tools.javac.util.Name,com.sun.tools.javac.code.Kinds$KindSelector)
  	at com.google.errorprone.util.FindIdentifiers.findIdent(FindIdentifiers.java:104)
  	at com.google.errorprone.fixes.SuggestedFixes.qualifyType(SuggestedFixes.java:289)
...
  	at java.base/java.lang.Thread.run(Thread.java:832)
  Caused by: java.lang.NoSuchMethodException: com.sun.tools.javac.comp.Resolve.findIdent(com.sun.tools.javac.comp.Env,com.sun.tools.javac.util.Name,com.sun.tools.javac.code.Kinds$KindSelector)
  	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2633)
  	at com.google.errorprone.util.FindIdentifiers.findIdent(FindIdentifiers.java:98)
  	... 185 more