Add 'error prone' static analysis tool: http://errorprone.info/ Integrates with gradle to give compile time warnings/errors, for example:
    ```
    % ./gradlew compileJava
    :
    :
    /home/dan/work/triplea/src/main/java/games/strategy/engine/random/PBEMDiceRoller.java:196:
warning: [WaitNotInLoop] Because of spurious wakeups, wait() must always
be called in a loop
            m_lock.wait();
                       ^
    (see http://errorprone.info/bugpattern/WaitNotInLoop)
    Did you mean 'while (!SwingUtilities.isEventDispatchThread()) {'?
    /home/dan/work/triplea/src/main/java/games/strategy/engine/lobby/server/NullModeratorController.java:106:
warning: [deprecation] setPassword(INode,String) in IModeratorController
has been deprecated
    public String setPassword(final INode node, final String
hashedPassword) {
                ^
    /home/dan/work/triplea/src/main/java/games/strategy/engine/lobby/server/db/HashedPassword.java:38:
error: [InvalidPatternSyntax] Invalid syntax used for a regular
expression: "." is a valid but useless regex
    return value.replaceAll(".", "*");
    ```